### ISSUE TITLE
Arm segfault (strlen)

### ISSUE THREAD

**Issue by Thann** [handshake-org/hnsd#12]
```
(gdb) r -p 4 -r 127.0.0.1:5300
Starting program: /home/pi/hnsd/hnsd -p 4 -r 127.0.0.1:5300
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
chain (0): chain is fully synced
addrman: added addr: 172.104.214.189:13038
addrman: added addr: 173.255.209.126:13038
addrman: added addr: 172.104.177.177:13038
addrman: added addr: 139.162.183.168:13038
pool: pool opened (size=4)
ns: root nameserver listening on: 127.0.0.1:15359
rs: recursive nameserver pointing to: 127.0.0.1@15359
rs: recursive nameserver listening on: 127.0.0.1:5300
starting event loop...

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/arm/armv6/strlen.S:26
26	../sysdeps/arm/armv6/strlen.S: No such file or directory.
(gdb) bt
#0  strlen () at ../sysdeps/arm/armv6/strlen.S:26
#1  0x76d97690 in _IO_vfprintf_internal (s=0x76e91d50 <_IO_2_1_stdout_>, format=0xb4c58 "peer %lu (%s): ", format@entry=0x7effb110 "\004", ap=..., ap@entry=...) at vfprintf.c:1637
#2  0x76d9cae0 in __printf (format=0xb4c58 "peer %lu (%s): ") at printf.c:33
#3  0x00022f64 in hsk_peer_log (peer=peer@entry=0xf93a8, fmt=0xb4d68 "connected\n") at src/pool.c:949
#4  0x0002361c in on_connect (conn=<optimized out>, status=0) at src/pool.c:1662
#5  0x0005a840 in uv__stream_connect (stream=0xf93b4) at src/unix/stream.c:1391
#6  uv__stream_io (loop=<optimized out>, w=0xf93f8, events=<optimized out>) at src/unix/stream.c:1308
#7  0x0005ec00 in uv__io_poll (loop=loop@entry=0xda610 <default_loop_struct>, timeout=2502) at src/unix/linux-core.c:400
#8  0x0005559c in uv_run (loop=0xda610 <default_loop_struct>, mode=UV_RUN_DEFAULT) at src/unix/core.c:368
#9  0x00013b64 in main ()
```

**Comment by chjj** [comment]
I think d88442b6164f61673afbf4bebadd738d1e901f1e should fix it.

**Comment by Thann** [comment]
Awesome! working on my ras pi now, thanks =]
